### ISSUE TITLE
unable install hexo-deployer-git  无法安装hexo-deployer-git

### ISSUE THREAD

**Issue by cliuyang** [hexojs/hexo-deployer-git#136]
Hello, I want to deploy my blog by hexo and github. so I install the hexo-deployer-git, but I can not install it successfully. I paste my environment below. what should I do?

我想使用hexo和GitHub来部署我的博客，所以我来安装hexo-deployer-git，但是总是安装不成功，我把我的环境截图贴在下面了。我应该怎么办？

![image](https://user-images.githubusercontent.com/39078310/60993164-83917480-a380-11e9-9fd4-d2b88df4e86d.png)

**Comment by JiangXL** [comment]
npm --registry=https://registry.npm.taobao.org install -g hexo-deployer-git --save

**Comment by JiangXL** [comment]
按提示修复？
` npm audit fix
`

**Comment by BrooksJoshua** [comment]
我也是hexo-deployer-git的问题, 试了好多次都还不行, 求解

**Comment by essesy** [comment]
我也想知道怎么办/(ㄒoㄒ)/~~

**Comment by SukkaW** [comment]
@cliuyang @BrooksJoshua @essesy 

Could you guys read English? If you can't, just copy the output into [Google Translate](https://translate.google.cn) or Baidu Translate.

From the log I could only see `hexo-deployer-git` has been successfully installed and you should be able to use `hexo d` after configure `_config.yml`.

I will close this issue since from the log pasted I could only see `hexo-deployer-git` has been successfully installed.
